# Basic operations

In [1]:
# import necessary libraries
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.resetwarnings()


### Example 1: Add two numbers
```
c = a + c
```

In [7]:
# create nodes in a graph

# declare two constant tensors
a = tf.constant(15)
b = tf.constant(61)

# add them
c = tf.add(a,b)
print(c) # The output is an abstract tensor, no computation has been made

Tensor("Add:0", shape=(), dtype=int32)


In [8]:
# create the session to run the graph

# Intialize the Session
sess = tf.Session()

# Print the result
print(sess.run(c))

# Close the session
sess.close()

76


### Example 2: Multiply two arrays

In [5]:
# Initialize two constants
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([6, 7, 8, 9, 10])

# Multiply
result = tf.multiply(a, b)

# Intialize the Session
sess = tf.Session()

# Print the result
print(sess.run(result))

# Close the session
sess.close()

[ 6 14 24 36 50]


In [6]:
# Initialize Session and run `result` using with
# In this case, the session is started, the operation is performed, and the the session is closed.
with tf.Session() as sess:
  output = sess.run(result)
  print(output)

[ 6 14 24 36 50]


### Example 3: Multiple operations
```
c = a + b
d = b - a
e = c * d
```

In [11]:
# First, we will define the inputs.
# placeholders, are values that are unassigned and that will be initialized by the session when you run it.

# define inputs, the data-type is set to float32
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# define operations
c = tf.add(a, b)
d = tf.subtract(b, a)
e = tf.multiply(c, d)

# perform the computation graph
with  tf.Session() as session:
    a_data, b_data = 5.0, 6.0
    
    # define inputs
    # In this case, we need to feed the graph with the two inputs. 
    # This is done by using a dict
    feed_dict = {a: a_data, b: b_data}
    
    # pass data in and run the computation graph in a session
    output = session.run(e, feed_dict=feed_dict)
    print(output) # 11

11.0


### Example 4: Variables and sessions

In [16]:
# Create a variable with an initial value
var = tf.Variable(3)

# Initializer of the variables
init_vars = tf.global_variables_initializer()

# Modify the value of the variable
operation = var.assign(5)

# Create two sessions
sess1 = tf.Session()
sess2 = tf.Session()

# Initialize variables in both sessions
sess1.run(init_vars)
sess2.run(init_vars)

# print value of var in session 1
print('Value of var in session 1 (before modification): {}'.format(sess1.run(var)) )

# Modify the value of var in session 1
sess1.run(operation)

# Print value of the var in both sessions
print('Value of var in session 1 (after modification): {}'.format(sess1.run(var))) 
print('Value of var in session 2: {}'.format(sess2.run(var)))

# Close Sessions
sess1.close()
sess2.close()

Value of var in session 1 (before modification): 3
Value of var in session 1 (after modification): 5
Value of var in session 2: 3


### Example 5: Constants and Variables

In [19]:
# define input
x = tf.constant([35, 40, 45])
y = tf.Variable(x + 5)


# Initialize variable
init_vars = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init_vars)
    print(session.run(y))

[40 45 50]


### Example 6: Variables and loops

In [20]:
# define variable and its initial value
x = tf.Variable(0)

# Initialize variable
init_vars = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init_vars)
    for i in range(5):
        x = x + 1
        print(session.run(x))

1
2
3
4
5


### Example 7: Value assignment

In [21]:
a = tf.Variable(1)
b = tf.constant(2)
c = a + b

assign = tf.assign(a, 5)

# In this case, the value of c depends on which of the operations 
# was executed first

sess = tf.Session()
for i in range(10):
    sess.run(tf.global_variables_initializer())
    print(sess.run([assign, c]))

[5, 7]
[5, 3]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]


In [22]:
# We can control that by controling the dependencies
a = tf.Variable(1)
b = tf.constant(2)
c = a + b

# In this case the addition is called before the assign
with tf.control_dependencies([c]):
    assign = tf.assign(a, 5)

sess = tf.Session()
for i in range(10):
    sess.run(tf.global_variables_initializer())
    print(sess.run([assign, c]))

[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]
[5, 3]


In [23]:
# We can control that by controling the dependencies
a = tf.Variable(1)
b = tf.constant(2)

assign = tf.assign(a, 5)

# In this case the assign is called before the addition
with tf.control_dependencies([assign]):
    c = a + b

sess = tf.Session()
for i in range(10):
    sess.run(tf.global_variables_initializer())
    print(sess.run([assign, c]))

[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]
[5, 7]


### Example 8: Conditionals

In [28]:
a = tf.constant(1)
b = tf.constant(2)

p = tf.constant(True)

# This is not allowed, it is necessary to use tf.cond to deal with if
if p:
    x = a + b
else:
    x = a * b

print(tf.Session().run(x))

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

In [26]:
a = tf.constant(1)
b = tf.constant(2)

p = tf.constant(True)

x = tf.cond(p, lambda: a + b, lambda: a * b)

print(tf.Session().run(x))

3


C:\Anaconda3\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
